name: Testing
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
#    SwiftLint:
#        runs-on: ubuntu-latest
#        steps:
#        - uses: actions/checkout@v1
#        - name: GitHub Action for SwiftLint
#          uses: norino-nomura/action-swiftlint@3.2.1

    Test:
        name: Testing Swift Package and iOS app
        runs-on: macOS-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v1

        - name: List available Xcode versions
          run: ls /Applications | grep Xcode

        - name: Select XCode version
          run: sudo xcode-select -switch /Applications/Xcode_13.2.app
        - name: Xcode version
          run: /usr/bin/xcodebuild -version

        - name: List Simulators
          run: xcrun simctl list --json devices available | grep iOS
          run: xcrun simctl list --json devices available | grep name

        - name: Run unit test
          run:  xcodebuild test -scheme Jakob\ Skov\ Sondergard\ CV\ \(iOS\) -project Jakob\ Skov\ Sondergard\ CV.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' | xcpretty && exit ${PIPESTATUS[0]}

#       - name: Build archive
#         run: |
#                xcodebuild -sdk iphoneos -project Jakob\ Skov\ Sondergard\ CV/Jakob\ Skov\ Sondergard\ CV.xcodeproj \
#                -configuration Release -scheme Jakob\ Skov\ Sondergard\ CV\ \(iOS\) \
#                -derivedDataPath DerivedData \
#                -archivePath DerivedData/Archive/Jakob\ Skov\ Sondergard\ CV archive
#       - name: Export archive
#         run: |
#                xcodebuild -exportArchive \
#                -archivePath DerivedData/Archive/Jakob\ Skov\ Sondergard\ CV.xcarchive
#                -exportOptionsPlist  provisioning/App-Store.plist \
#                -exportPath DerivedData/ipa
#
#        - name: Deploy App to Apple
#          run: |
#                xcrun altool --upload-app --type ios \
#                --file DerivedData/ipa/Jakob\ Skov\ Sondergard\ CV.ipa \
#                --username "${{ secrets.appstore_connect_usename }}" \
#                --password "${{ secrets.appstore_connect_password }}" --verbose
#
#    -name: Install GPG
#        run: brew install gnupg
#
#    - name: Decrypt large secret
#        run: ./provisioning/import_provisioning.sh
#        env:
#            PROVISIONING_PASSWORD: ${{ secrets.provisioning_password }}
#
##      - name: Testing Swift package
##        run: exec ./.github/scripts/test_swift_package.sh
#
#      - name: Testing iOS app
#        run: exec ./.github/scripts/test_app.sh
